create table recipe (
    id integer primary key generated by default as identity,
    title text not null,
    minutes integer not null,
    instructions text not null,
    image text,
    date_modified timestamp default now() not null
);


